agents:
  ovis:
    model_name: AIDC-AI/Ovis2-8B
    device: 0
  minicpm_o:
    model_name: openbmb/MiniCPM-o-2_6
    device: 1
  qwenvl:
    model_name: Qwen/Qwen2.5-VL-7B-Instruct
    device: 2

llm:
  device: 3

dataset:
  name: aokvqa